dataset_name: 'SWaT'
data_path: 'E:/Code_Zero/raw_data/Swat_physical/SWaT_Dataset_Attack_v0.csv'
# './raw_data/Swat_physical/SWaT_Dataset_Attack_v0.csv'


num_features: 51
valid_features: 44
# label: false


batch_size: 16
eval_interval: 1

# TODO: windowsize, stridesize, shuffle, n_workers...