defaults:
    - _self_
    - dataset: SWaT
    - algorithm: LSTM_AE
    - train: normal

# meta-configurations
wandb:
    project: 'Multivariant Time Series Anomaly Detection'

device: 'cuda'
seed: 42